Homework01
anastasiiaCher/cs102-2024 pull request #100
Opened 2024-10-31 12:55 UTC by emopudge

2024-10-31 12:57 UTC, anastasiiaCher commented
Допзадание для защиты
Шифр Атбаш (рус)

Древний шифр подстановки, в котором буква шифруется с помощью ее отражения с другого конца алфавита, то есть первой букве соответствует последняя, второй - предпоследняя и так далее. Правило шифрования состоит в замене
$i$-й буквы алфавита буквой с номером $n−i+1$, где $n$ — число букв в алфавите. Напишите функцию `encrypt_atbash(plaintext)` для шифрования текста на русском. Разместите функцию в отдельном файле в папке `homework01` ветки `homework01` вашего репозитория.

2024-11-12 13:15 UTC, anastasiiaCher requested changes
Некоторые части решения стоит доработать

2024-11-12 13:15 UTC, anastasiiaCher commented on homework01/.idea/.gitignore
Папка `.idea` не должна оказываться с гитхабе, обычно такое случается, если вы добавляете файлы с помощью команды `git add .`
Так не стоит делать

2024-11-12 13:15 UTC, anastasiiaCher commented on homework01/atbash.py
Из-за того, что часть букв присваивается конкретным буквам алфавита, часть тестов не прошла, за защиту 1 балл из 2

2024-11-12 13:15 UTC, anastasiiaCher commented on homework01/rsa.py
> +            break
Можно заменить на `return False`
И тогда `count` и все манипуляции с ним не нужны

2024-11-12 13:15 UTC, anastasiiaCher commented on homework01/rsa.py
> +            d += 1
Это потенциально очень долгий цикл. В этой задаче лучше не делать полный перебор

2024-11-12 13:15 UTC, anastasiiaCher commented on homework01/vigenere.py
В этом файле стоит обойтись без списков, строк более чем достаточно

2024-11-15 08:04 UTC, emopudge commented on homework01/atbash.py
там просто была трудность с буквой Ё, так как ее вообще куда-то в конец алфавита запихнули в кодировке, поэтому получалось некорректное отображение(

2024-12-23 11:56 UTC, anastasiiaCher commented on homework01/.idea/.gitignore
По названию файла, можно несколько перечислить после git add через пробел

2024-12-23 11:56 UTC, closed without merging