homework02 1.1 Толкачев Т.С.
anastasiiaCher/cs102-2024 pull request #112
Opened 2024-11-11 20:59 UTC by tolkts

Реализация решателя и генератора судоку на Python.

2024-11-19 16:52 UTC, anastasiiaCher commented
За защиту 3 балла
Но пул-реквест стоило сделать с целью влить ветку не в `master`, а в `homework02`

2024-11-28 10:30 UTC, Paralics reviewed
Я изучил файл sudoku.py, ниже привел несколько рекомендаций по его изменению для большего соответствия pep 8.

2024-11-28 11:17 UTC, Paralics reviewed
Я изучил файл sudoku.py, ниже привел несколько рекомендаций по его изменению для большего соответствия pep 8.

2024-11-28 11:17 UTC, Paralics commented on homework02/sudoku.py
> +    return [*grid[y * 3][x * 3 : x * 3 + 3], *grid[y * 3 + 1][x * 3 : x * 3 + 3], *grid[y * 3 + 2][x * 3 : x * 3 + 3]]
Длина строки превышает рекомендованную, разбиение строки на несколько задач сделает код более читаемым.

2024-11-28 11:17 UTC, Paralics commented on homework02/sudoku.py
> +    return [grid[i][pos[1]] for i in range(len(grid))]
Здесь используется код схожий с реализованной вами функцией *transpose*, возможно имеет смысл применить ее.

2024-11-28 11:17 UTC, Paralics commented on homework02/sudoku.py
> +    return True
Функции не хватает доктестов.

2024-11-28 11:17 UTC, Paralics commented on homework02/sudoku.py
> +    return [[grid[i][j] for i in range(len(grid))] for j in range(len(min(grid, key=len)))]
Функции не хватает доктестов.

2024-11-28 11:17 UTC, Paralics commented on homework02/sudoku.py
> +        print("".join(grid[row][col].center(width) + ("|" if str(col) in "25" else "") for col in range(9)))
Длина строки превышает рекомендуемую. Для большей читаемости имеет смысл оставить функцию *display* в изначальном виде.

2024-11-28 11:17 UTC, Paralics commented on homework02/sudoku.py
> +            if symbol in get_row(copy, (i, j)) or symbol in get_col(copy, (i, j)) or symbol in get_block(copy, (i, j)):
Длина строки превышает рекомендуемую. В целях повышения читаемости имеет смысл разбить строку на несколько.

2024-12-23 19:17 UTC, anastasiiaCher requested changes

2024-12-23 19:17 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return result
Это лучше сделать списковым включением

2024-12-23 19:17 UTC, anastasiiaCher commented on homework02/sudoku.py
> +            r.shuffle(result[6:9])
Можно заменить на более компактный переборный цикл

2024-12-23 19:17 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return [[grid[i][j] for i in range(len(grid))] for j in range(len(min(grid, key=len)))]
А юнит-тесты вы для нее написали?

2025-01-10 13:27 UTC, anastasiiaCher approved these changes

2025-01-10 13:27 UTC, closed without merging