Homework02
anastasiiaCher/cs102-2024 pull request #113
Opened 2024-11-12 22:35 UTC by Paralics

Реализовал все функции в лабораторной работе. 

Позаимствовал у себя же из классной работы вспомогательную функцию matrix_transposition.

Со вспомогательными, решением и проверкой правильности решения все достаточно прямолинейно.

Для генерации судоку написал вспомогательную функцию shuffle_grid, перемешивающую случайным образом строки в рамках каждого блока строк и столбцы в рамках каждого блока столбцов (пригодились транспозиции аж в двух смыслах этого слова). 

generate_sudoku реализовал следующим образом: из перемешанного тривиального решения судоку выбирается н различных клеток, и их значения вписываются в соответствующие клетки пустого пазла. (Таким образом я точно получаю только решаемые судоку, однозначно не каждое из таких, но много. Наверное, если бы в рамках shuffle_grid также менял попарно k и k + 1, получал бы все, но доказать или опровергнуть сходу не получилось + это прилично замедлило бы функцию).

2024-11-19 16:11 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/112
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-19 16:47 UTC, leetrat reviewed
Я просмотрел файл sudoku.py и оставил пару рекомендаций, при соблюдении которых этот код будет лучше соответствовать PEP8, а также будет более удобен для тестирования и использования другими разработчиками.

2024-11-19 16:47 UTC, tolkts commented on homework02/sudoku.py
> +    correct = set("123456789")
Можно объявить данную переменную без преобразования строки в set, а при помощи генератора в фигурных скобках

2024-11-19 16:47 UTC, tolkts commented on homework02/sudoku.py
> +        column = "".join(grid[row]).find(".")
Можно проверить существование элемента в списке при помощи оператора in, не преобразовывая его в строку

2024-12-23 19:20 UTC, anastasiiaCher requested changes

2024-12-23 19:20 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    correct = set("123456789")
Вариант со строкой быстрее

2024-12-23 19:20 UTC, anastasiiaCher commented on homework02/sudoku.py
> +def shuffle_grid(grid: list[list[str]]) -> list[list[str]]:
Юнит-тест

2025-01-10 13:25 UTC, anastasiiaCher approved these changes
Написали доктесты, а не юнит-тесты, а так ок

2025-01-10 13:25 UTC, closed without merging