homework02 Дмитриева Е.А. 1.2
anastasiiaCher/cs102-2024 pull request #118
Opened 2024-11-14 17:47 UTC by Katharine-Posh

2024-11-28 12:39 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/131
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-28 14:30 UTC, ilonabond commented on homework02/sudoku.py
> +        print("".join(grid[row][col].center(width) + ("|" if str(col) in "25" else "") for col in range(9)))
строка превышает количество разрешенных символов

2024-11-28 14:30 UTC, ilonabond commented on homework02/sudoku.py
>  def read_sudoku(path: tp.Union[str, pathlib.Path]) -> tp.List[tp.List[str]]:
лучше использовать | вместо , (path: str | pathlib.Path)

2024-11-28 14:30 UTC, ilonabond commented on homework02/sudoku.py
> +    y, x = pos[0] // 3, pos[1] // 3
переменные x, y лучше заменить на более осмысленные

2024-11-28 14:30 UTC, ilonabond commented on homework02/sudoku.py
> +    return [*grid[y * 3][x * 3 : x * 3 + 3], *grid[y * 3 + 1][x * 3 : x * 3 + 3], *grid[y * 3 + 2][x * 3 : x * 3 + 3]]
нарушена читаемость кода, лучше написать так: 
start_row, start_col = row_block * 3, col_block * 3
return [
    grid[start_row][start_col:start_col + 3] +
    grid[start_row + 1][start_col:start_col + 3] +
    grid[start_row + 2][start_col:start_col + 3]
]

2024-11-28 14:30 UTC, ilonabond commented on homework02/sudoku.py
>      digits = [c for c in puzzle if c in "123456789."]
лучше заменить переменную "с" на более осмысленную

2024-11-28 14:30 UTC, ilonabond commented on homework02/sudoku.py
> +    return [values[i : i + line_len] for i in range(0, len(values), line_len)]
нет пробела между i : i

2024-11-28 14:30 UTC, ilonabond commented on homework02/sudoku.py
> +    set_first = set("123456789")
лучше заменить переменные set_first и set_second на all_possible_values и existing_values

2024-11-28 14:30 UTC, ilonabond commented on homework02/sudoku.py
>  import typing as tp
Импорты должны быть разделены по категориям, импорты стандартной библиотеки pathlib и random должны быть наверху, отдельно от typing

2024-12-24 09:13 UTC, anastasiiaCher requested changes

2024-12-24 09:13 UTC, anastasiiaCher commented on homework02/sudoku.py
>  import typing as tp
typing - тоже часть стандартной библиотеки

2024-12-24 09:13 UTC, anastasiiaCher commented on homework02/sudoku.py
>  def read_sudoku(path: tp.Union[str, pathlib.Path]) -> tp.List[tp.List[str]]:
Эквивалентно

2024-12-24 09:13 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    y, x = pos[0] // 3, pos[1] // 3
x, y абсолютно нормальные

2024-12-24 09:13 UTC, anastasiiaCher commented on homework02/sudoku.py
> +                return False
Проще сравнивать  множества допустимых и реальных значений, чем искать точки, но подход интересный, пускай остается

2025-01-10 13:23 UTC, anastasiiaCher approved these changes

2025-01-10 13:23 UTC, closed without merging