Homework02 K24 1.1 Попов А.А.
anastasiiaCher/cs102-2024 pull request #123
Opened 2024-11-18 18:07 UTC by loxarr

2024-11-19 16:08 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/124
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-19 17:21 UTC, elkulakova commented on homework02/sudoku.py
> +    while still > N:
эффективнее и правильнее использовать for, просто с шагом -1

2024-12-23 19:10 UTC, anastasiiaCher requested changes
Очень советую доработать в соответствии с комментариями

2024-12-23 19:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return gr
Можно сразу вернуть `[values[i : i + n] for i in range(0, len(values), n)]`

2024-12-23 19:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    gr = [grid[i][pos[1]] for i in range(len(grid))]
Лучше сразу вернуть включение, а то вы вместо колонки группу создаете)

2024-12-23 19:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return arr
Тоже можно сразу вернуть

2024-12-23 19:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    flag = 0
Можно и нужно без флагов

2024-12-23 19:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    pos = None
Эта переменная не нужна

2024-12-23 19:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +                pos = (i, j)
просто `return i, j`

2024-12-23 19:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return pos
`return None`

2024-12-23 19:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return values
Не слишком читаемая реализация проверки. Лучше без вот этого `chr(i + 48)`

2024-12-23 19:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +                solve(grid)
Лучше куда-то сохранять результат

2024-12-23 19:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +            else:
Можно без `else`, оно недостижимое

2024-12-23 19:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    False
🫶

2024-12-23 19:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return flag
Лучше через сравнение множеств значений в строках, столбцах и блоках. Флаги не для питона все-таки

2024-12-23 19:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    ]
Это лучше сгенерировать, а не хардкодить

2025-01-25 07:50 UTC, closed without merging