homework02 K24 1.1 Грачев Д.А.
anastasiiaCher/cs102-2024 pull request #124
Opened 2024-11-18 18:18 UTC by DimaGrach1

2024-11-19 16:08 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/125
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-19 16:52 UTC, loxarr reviewed
Для защиты лабораторной работы 3 я посмотрел файл и оставил комментарии, чтобы код больше соответствовал PEP8

2024-11-19 17:00 UTC, anastasiiaCher requested changes

2024-11-19 17:00 UTC, anastasiiaCher commented on homework02/sudoku.py
>  def check_solution(solution: tp.List[tp.List[str]]) -> bool:
Для всех новых функций надо написать тесты

2024-11-19 17:00 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    grid[n_area1 * 3 : n_area1 * 3 + 3], grid[n_area2 * 3 : n_area2 * 3 + 3] = (
Правки с пробелами вносить не нужно

2024-11-19 17:00 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        print("".join(grid[row][col].center(width) + ("|" if str(col) in "25" else "") for col in range(9)))
Можно не трогать

2024-12-23 18:58 UTC, anastasiiaCher approved these changes

2024-12-23 18:59 UTC, closed without merging