Homework02 1.1 Трофименко Е.А
anastasiiaCher/cs102-2024 pull request #125
Opened 2024-11-18 21:46 UTC by EgorTrofimenko

2024-11-19 16:09 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/120
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-19 16:57 UTC, DimaGrach1 commented on homework02/sudoku.py
> +    return res
return [row[pos[1]] for row in grid]

Простой цикл можно выполнить в виде спискового включения

2024-11-19 16:57 UTC, DimaGrach1 commented on homework02/sudoku.py
> +            sol_copy[i][j] = "."
Вместо for _ in range(len(val)) можно использовать enumerate, как это было представлено в функции find_empty_positions

2024-11-19 16:57 UTC, DimaGrach1 commented on homework02/sudoku.py
> +            sol_copy[i][j] = "."
Плюс переприсваивание двух переменных можно записать в одну строку вместо двух

2024-11-19 16:57 UTC, DimaGrach1 commented on homework02/sudoku.py
> +            return next
Имя переменной совпадает с именем функции next()

2024-11-19 16:57 UTC, DimaGrach1 commented on homework02/sudoku.py
> +        *grid[coord1 * 3 + 2][coord2 * 3 : coord2 * 3 + 3],
Согласно стандарту PEP8 перед двоеточием в срезах не должно быть пробела

2024-11-19 17:10 UTC, anastasiiaCher requested changes

2024-11-19 17:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return matrix
Можно сразу писать списковое включение в `return`

2024-11-19 17:10 UTC, anastasiiaCher commented on homework02/sudoku.py
> +            sol_copy[i][j] = "."
Второй коммент править не нужно

2024-11-19 17:10 UTC, anastasiiaCher commented on homework02/sudoku.py
>  def check_solution(solution: tp.List[tp.List[str]]) -> bool:
Функцию проще реализовать так: проверить, что множество значений в каждом столбце, строке и блоке совпадает с множеством допустимых значений.

2024-12-23 18:54 UTC, anastasiiaCher approved these changes

2024-12-23 18:59 UTC, closed without merging