Homework02 K24 1.3 Усенко Е. В.
anastasiiaCher/cs102-2024 pull request #126
Opened 2024-11-19 17:21 UTC by Anr1st

2024-11-28 13:02 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/127
Сделать ревью можно во вкладе files changed указанного репозитория

2024-12-03 22:59 UTC, crys00n commented on homework02/sudoku.py
> +    return grid[row]
можно просто `return grid[pos[0]]`

2024-12-03 22:59 UTC, crys00n commented on homework02/sudoku.py
> +    return [grid[r][c] for r in range(start_row, start_row + 3) for c in range(start_col, start_col + 3)]
очень длинная строка
т.к. тут квадратные скобки, можно воспользоваться переносом, чтобы сделать более читабельным

2024-12-03 22:59 UTC, crys00n commented on homework02/sudoku.py
> +        for c in range(len(grid)):
вместо `range(len())` лучше использовать `enumerate()`

2024-12-03 22:59 UTC, crys00n commented on homework02/sudoku.py
> +    return [row[col] for row in grid]
можно в одну строчку вот так `return [col[pos[1]] for _, col in enumerate(grid)]`

2024-12-03 22:59 UTC, crys00n commented on homework02/sudoku.py
> +    return possible_values - used_values
можно избавиться от лишних переменных и сделать все в одну строчку, пользуясь переносом, чтобы оставить читабельность кода: 
`return set("123456789") - (set(get_row(grid, pos))
                               | set(get_col(grid, pos))
                               | set(get_block(grid, pos)))`

2024-12-03 22:59 UTC, crys00n commented on homework02/sudoku.py
> +    return possible_values - used_values
гит, к сожалению, не показывает перенос(

2024-12-03 22:59 UTC, crys00n commented on homework02/sudoku.py
> +import random
импорты, как правило, помещаются в начале файла

2024-12-23 18:50 UTC, anastasiiaCher requested changes

2024-12-23 18:50 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return grid[row]
Можно, но и исходный вариант хороший

2024-12-23 18:50 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return [row[col] for row in grid]
Оба варианта хорошие, в исходном выше читаемость

2024-12-23 18:50 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return possible_values - used_values
Оба варианта хорошие

2024-12-23 18:50 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        column = [solution[row][col] for row in range(9)]
Можно использовать написанную ранее функцию `get_col`

2024-12-23 18:50 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    for block_row in range(0, 9, 3):
Можно использовать написанную ранее функцию `get_block`

2024-12-23 18:50 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    solve(grid)
Лучше куда-то сохранить решенную сетку

2024-12-23 18:51 UTC, anastasiiaCher commented
Ревью хорошее

2025-01-25 07:50 UTC, closed without merging