homework02 1.1 Величко АЮ
anastasiiaCher/cs102-2024 pull request #127
Opened 2024-11-19 22:25 UTC by crys00n

Написал функции для чтения/решения/проверки решения/генерации судоку.

2024-11-28 13:02 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/126
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-30 23:47 UTC, Anr1st commented on homework02/sudoku.py
Можно избавиться от лишних вызовов функций:
`   all_values = set("123456789")`
`    for i in range(len(solution)):`
`        if (`
`           set(get_row(solution, (i, 0))) != all_values or`
`            set(get_col(solution, (0, i))) != all_values or`
`            set(get_block(solution, (i // 3 * 3, i % 3 * 3))) != all_values`
`        ):`
`            return False`
`    return True`

2024-12-23 18:46 UTC, anastasiiaCher requested changes

2024-12-23 18:46 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return row
Можно сразу `return grid[pos[0]]`

2024-12-23 18:46 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    pos = tuple()  # type: tuple
Эта строчка не нужна

2024-12-23 18:46 UTC, anastasiiaCher commented on homework02/sudoku.py
> +                pos = (i, j)
Можно сразу `return i, j`

2024-12-23 18:46 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return pos
А тут тогда `return None`

2024-12-23 18:46 UTC, anastasiiaCher commented on homework02/sudoku.py
Все равно много действий

2024-12-23 18:46 UTC, anastasiiaCher commented on homework02/sudoku.py
Оба варианта хорошие

2024-12-23 18:51 UTC, anastasiiaCher commented
Ревью хорошее

2025-01-14 10:41 UTC, anastasiiaCher approved these changes

2025-01-14 10:41 UTC, closed without merging