homework02 1.3 Сафонова Л.М.
anastasiiaCher/cs102-2024 pull request #128
Opened 2024-11-20 08:18 UTC by LiudmilaSafonova

В ходе лабораторной работы я написала функции, позволяющие решать и создавать судоку.

2024-11-22 15:37 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/130
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-22 16:20 UTC, krmazn reviewed
Я правда придирался как мог. Красивое решение!

2024-11-22 16:20 UTC, krmazn commented on homework02/sudoku.py
> +    return None
Рекомендуемый формат вывода - список. Если функция завершает работу досрочно - пускай она выведет пустой массив, а не None

2024-11-22 16:20 UTC, krmazn commented on homework02/sudoku.py
> +    N = min(N, 81)
Переменные, названные заглавной буквой, не соответствуют общепринятому стилю нейминга snake_case

2024-12-24 09:35 UTC, anastasiiaCher requested changes

2024-12-24 09:35 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return next(((i, j) for i in range(len(grid)) for j in range(len(grid[i])) if grid[i][j] == "."), None)
Интересное решение, но лучше сделать его более читаемым

2024-12-24 09:35 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    all_values -= {el for el in get_row(grid, pos) if el in "123456789"}
Можно же просто вычесть множество значений в ряде/блоке: `all_values -= set(get_row(grid, pos))`

2024-12-24 09:35 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return None
Шаблон допускает возврат `None`

2024-12-24 09:35 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    N = min(N, 81)
Можно капсом, если это - константа

2025-01-10 13:20 UTC, anastasiiaCher approved these changes

2025-01-10 13:20 UTC, closed without merging