Homework02 1.3 Кармазин А.З.
anastasiiaCher/cs102-2024 pull request #130
Opened 2024-11-21 22:02 UTC by krmazn

2024-11-22 16:11 UTC, LiudmilaSafonova commented on homework02/sudoku.py
> +    pos: tuple
Возможно, следует задать пустой кортеж так: pos = ()

2024-11-22 16:12 UTC, LiudmilaSafonova commented on homework02/sudoku.py
> +    for i in range(len(grid)):
Сейчас цикл со счетчиком, лучше заменить, используя enumerate
for i, el in enumerate(grid):
    for j, elem in enumerate(el):
        if elem == ".":
            pos = (i, j)

2024-11-22 16:23 UTC, LiudmilaSafonova commented on homework02/sudoku.py
> +    correct_grid = tuple(
Можно обойтись без tuple
returned_grid = [
            ["5", "3", "4", "6", "7", "8", "9", "1", "2"],
            ["6", "7", "2", "1", "9", "5", "3", "4", "8"],
            ["1", "9", "8", "3", "4", "2", "5", "6", "7"],
            ["8", "5", "9", "7", "6", "1", "4", "2", "3"],
            ["4", "2", "6", "8", "5", "3", "7", "9", "1"],
            ["7", "1", "3", "9", "2", "4", "8", "5", "6"],
            ["9", "6", "1", "5", "3", "7", "2", "8", "4"],
            ["2", "8", "7", "4", "1", "9", "6", "3", "5"],
            ["3", "4", "5", "2", "8", "6", "1", "7", "9"]]

2024-11-22 16:24 UTC, krmazn commented on homework02/sudoku.py
> +    correct_grid = tuple(
Tuple сделан для того, чтобы изменения в List не затрагивали хардкод

2024-11-22 16:29 UTC, LiudmilaSafonova commented on homework02/sudoku.py
> +    val_0 = tuple("123456789")
Можно сразу val_0 = list("123456789")

2024-11-22 16:41 UTC, LiudmilaSafonova commented on homework02/sudoku.py
> +    if potential_values == set():
Можно if not potential_values

2024-11-23 09:47 UTC, LiudmilaSafonova commented on homework02/sudoku.py
> +    return array
В функциях group, get_row и get_col можно не создавать отдельную переменную для вывода

2024-12-24 09:31 UTC, anastasiiaCher requested changes

2024-12-24 09:31 UTC, anastasiiaCher commented on homework02/sudoku.py
> +                return pos
`return i, j`

2024-12-24 09:31 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    val_0 = tuple("123456789")
А что такое `val_0`?

2024-12-24 09:31 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    correct_grid = tuple(
> Tuple сделан для того, чтобы изменения в List не затрагивали хардкод

Красиво

2025-01-10 13:18 UTC, anastasiiaCher requested changes

2025-01-10 13:18 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return array
Не исправили же

2025-01-10 13:18 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    else:
Можно без `else`, он недостижимый

2025-01-10 13:18 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    pos: tuple
А зачем вообще эта переменная?

2025-01-10 13:19 UTC, anastasiiaCher approved these changes

2025-01-10 13:19 UTC, closed without merging