homework02 1.2 Бондар И.А.
anastasiiaCher/cs102-2024 pull request #131
Opened 2024-11-22 08:26 UTC by ilonabond

2024-11-28 12:39 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/118
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-29 13:55 UTC, Katharine-Posh commented on homework02/sudoku.py
> +    return None
Стоило бы использовать enumerate(grid) и enumerate(p), переписав функцию чуть-чуть

2024-11-29 14:06 UTC, Katharine-Posh commented on homework02/sudoku.py
> -    # TODO: Add doctests with bad puzzles
Стоит добавить доктесты для проверки функции

2024-11-29 14:10 UTC, Katharine-Posh commented on homework02/sudoku.py
> +    return None
Лучше было бы возвращать пустой массив, а не None, в соответствии с форматом вывода

2024-12-24 09:08 UTC, anastasiiaCher requested changes

2024-12-24 09:08 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return None
Формат возврата допускает возврат `None`

2025-01-10 13:15 UTC, anastasiiaCher approved these changes

2025-01-10 13:15 UTC, closed without merging