Homework02 K24 1.2 Маряшина Ю. С.
anastasiiaCher/cs102-2024 pull request #137
Opened 2024-11-25 14:07 UTC by Juliewh

2024-11-28 13:33 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/151
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-28 21:22 UTC, yatayusha commented on homework02/sudoku.py
> +        print("".join(grid[row][col].center(width) + ("|" if str(col) in "25" else "") for col in range(9)))
По стандарту pep8 длина строчки кода должна быть не более 79 символов. Лучше будет перенести часть строки
```suggestion
        print("".join(grid[row][col].center(width) + 
                  ("|" if str(col) in "25" else "") for col in range(9)))
```

2024-12-24 08:50 UTC, anastasiiaCher requested changes

2024-12-24 08:50 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return possible_values
`return permissible_set - used_values`

2024-12-24 08:50 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    solved_grid = [row[:] for row in empty_grid]
Проще сохранять решенный судоку в новую переменную

2024-12-24 08:52 UTC, anastasiiaCher approved these changes

2024-12-24 08:52 UTC, closed without merging