Homework02 Соклаков Е.А. 1.3
anastasiiaCher/cs102-2024 pull request #138
Opened 2024-11-25 15:29 UTC by Astmatik001

2024-11-28 12:56 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/143
Сделать ревью можно во вкладе files changed указанного репозитория

2024-12-25 08:47 UTC, krevetkasofa requested changes

2024-12-25 08:47 UTC, krevetkasofa commented on homework02/sudoku.py
> +
можно убрать пустую строку

2024-12-25 08:47 UTC, krevetkasofa commented on homework02/sudoku.py
> +        str(i) for i in range(1, 10, 1) if ((str(i) not in row) and (str(i) not in col) and (str(i) not in block))
для лучшей читаемости if можно снести на след строку

2024-12-25 08:47 UTC, krevetkasofa commented on homework02/sudoku.py
> +    for i in range(len(grid)):
лучше заменить на enumerate

2024-12-25 08:47 UTC, krevetkasofa commented on homework02/sudoku.py
> +        block = get_block(solution, (block_row, block_col))
можно сразу включить решение в block, чтобы код был компактнее:  block = get_block(solution, (i // 3 * 3, i % 3 * 3))

2025-01-10 13:00 UTC, anastasiiaCher requested changes

2025-01-10 13:00 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return output
`return [grid[i][col] for i in range(len(grid))]`

2025-01-10 13:00 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        str(i) for i in range(1, 10, 1) if ((str(i) not in row) and (str(i) not in col) and (str(i) not in block))
Третий аргумент в `range` равен 1 по умолчанию

2025-01-10 13:00 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    pos2 = pos
`pos2` - это что?

2025-01-10 13:00 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        block = get_block(solution, (block_row, block_col))
Оба варианта ок

2025-01-25 07:49 UTC, closed without merging