Попкова Сафия, 1.2
anastasiiaCher/cs102-2024 pull request #143
Opened 2024-11-26 23:34 UTC by krevetkasofa

1. Прочитали Пазл
2. Разбили на строки, колоны и тд
3. Решили судоку
4. проверили решение
5. сгенерировали новый пазл

2024-11-28 12:56 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/138
Сделать ревью можно во вкладе files changed указанного репозитория

2024-12-12 10:09 UTC, Astmatik001 requested changes
43: for i in range(len(values)) -> for i, _ in enumerate(values)
103: for i in range(len(grid)) -> for i, _ in enumerate(grid)
104: for j in range(len(grid[i])) -> for j, _ in enumerate(grid[i])
123: for i in range(len(grid)) -> for i, _ in enumerate(grid)

2024-12-24 09:23 UTC, anastasiiaCher requested changes

2024-12-24 09:23 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return result
Лучше заменить на списковое включение

2024-12-24 09:23 UTC, anastasiiaCher commented on homework02/sudoku.py
> +            values.discard(grid[i][j])
Можно сильно упростить и сократить, если использовать `get_col`, `get_row`, `get_block`

2024-12-24 09:23 UTC, anastasiiaCher commented on homework02/sudoku.py
> +                return False
Лучше использовать `get_row`, `get_col`, `get_block`. Они как раз для этого и есть в этой работе)

2024-12-24 09:23 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    for i in range(len(grid)):
Лучше `enumerate`

2024-12-24 09:23 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        for j in range(len(grid[i])):
Лучше `enumerate`

2025-01-10 12:55 UTC, anastasiiaCher approved these changes

2025-01-10 12:55 UTC, closed without merging

2025-01-10 13:02 UTC, anastasiiaCher commented
Ревью кода коллеги в целом ок