Homework02 1.2 Цыганков
anastasiiaCher/cs102-2024 pull request #144
Opened 2024-11-27 15:02 UTC by DamianITMO

2024-11-28 12:36 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/133
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-28 14:17 UTC, AnetteZh commented on homework02/sudoku.py
> +    return [*grid[y * 3][x * 3 : x * 3 + 3], *grid[y * 3 + 1][x * 3 : x * 3 + 3], *grid[y * 3 + 2][x * 3 : x * 3 + 3]]
Тут я бы добавила переменные начала строки и столбца для улучшения читаемости (вместо того, чтобы подставлять в индексы grid x и y) и распаковку каждого списка писала на отдельной строчке

2024-11-28 14:33 UTC, AnetteZh commented on homework02/sudoku.py
> +    readyplane = [["." for i in range(9)] for i in range(9)]
Все переменные, которые не используются, можно заменить на нижнее подчеркивание

2024-11-28 14:37 UTC, AnetteZh commented on homework02/sudoku.py
> +    return [grid[i][pos[1]] for i in range(len(grid))]
Тут можно не использовать len(), а сразу перебирать элементы из grid

2024-12-01 21:17 UTC, DamianITMO commented on homework02/sudoku.py
> +    return [*grid[y * 3][x * 3 : x * 3 + 3], *grid[y * 3 + 1][x * 3 : x * 3 + 3], *grid[y * 3 + 2][x * 3 : x * 3 + 3]]
А зачем распаковка на отдельных строчках, если тут уже return?

2024-12-01 21:19 UTC, DamianITMO commented on homework02/sudoku.py
> +    readyplane = [["." for i in range(9)] for i in range(9)]
Немного не понял. Это же заготовка итоговой доски. Зачем её на подчеркивание менять?

2024-12-01 21:25 UTC, DamianITMO commented on homework02/sudoku.py
> +    return [grid[i][pos[1]] for i in range(len(grid))]
Но мы же возвращаем только одну "линию" доски. А для этого нужен len().

2024-12-24 09:02 UTC, anastasiiaCher requested changes

2024-12-24 09:02 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return [values[ii : ii + n] for ii in range(0, len(values), n)]
Двойными буквами странно называть переменные, название `i` довольно стандартное

2024-12-24 09:02 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return [grid[i][pos[1]] for i in range(len(grid))]
Не нужен, можно так: `return [row[pos[1]] for row in grid]`

2024-12-24 09:02 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return [*grid[y * 3][x * 3 : x * 3 + 3], *grid[y * 3 + 1][x * 3 : x * 3 + 3], *grid[y * 3 + 2][x * 3 : x * 3 + 3]]
Для читаемости. Строку в `return` можно разбивать на несколько

2024-12-24 09:02 UTC, anastasiiaCher commented on homework02/sudoku.py
> +            return vorwärts
Лучше давать имена переменным на одном языке. А то у вас где-то немецкий, где-то русский транслит, где-то английский. Не способствует повышению читаемости. И если имя переменной из двух слов, разбивайте их нижним подчеркиванием: не `readyplane`, а `ready_plane`

2024-12-24 09:02 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    readyplane = [["." for i in range(9)] for i in range(9)]
У вас `i` не используется при вычислении значения выражения, поэтому можно так: 
```
[["." for _ in range(9)] for _ in range(9)]
```

2025-01-25 07:49 UTC, closed without merging