Homework02 Сармусокова А.С. 1.2
anastasiiaCher/cs102-2024 pull request #145
Opened 2024-11-27 19:05 UTC by amina339

2024-11-28 12:35 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/147
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-28 13:04 UTC, mariapurpur reviewed
Оставлены рекомендации по коду.

2024-11-28 14:42 UTC, mariapurpur reviewed
Второй комментарий.

2024-12-24 08:42 UTC, anastasiiaCher requested changes

2024-12-24 08:42 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return coll
`return [x[pos[1]] for x in grid]`

2024-12-24 08:42 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return set(exn)
`return {x for x in num if x not in get_block(grid, pos) + get_col(grid, pos) + get_row(grid, pos)}`

2024-12-24 08:42 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        grid[pose[0]][pose[1]] = i
Оба варианта ок

2025-01-10 12:53 UTC, anastasiiaCher approved these changes

2025-01-10 12:53 UTC, closed without merging