Homework02 Скоринцева Таисия 1.2
anastasiiaCher/cs102-2024 pull request #146
Opened 2024-11-27 20:20 UTC by yatayusha

1) Реализовала ряд функций для разбиение пазла на удобные блоки: строки, столбцы, квадратные блоки
2) Реализовала ряд функций для решение пазла
3) Реализовала функцию для проверки решения и поиска плохих пазлов
4) Реализовала генерацию нового пазла Судоку

2024-11-28 13:35 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/137
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-28 14:35 UTC, Juliewh commented on homework02/sudoku.py
> +        print("".join(grid[row][col].center(width) + ("|" if str(col) in "25" else "") for col in range(9)))
строка слишком длинная, можно переписать в несколько строк для читаемости

2024-11-28 14:44 UTC, Juliewh commented on homework02/sudoku.py
> +        for k, tochka in enumerate(row):
"tochka" - название переменной специфично для русского языка, лучше создавать переменные в едином стиле и чтобы они отражали свою суть

2024-12-24 08:46 UTC, anastasiiaCher requested changes

2024-12-24 08:46 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return column
`return [row[pos[1]] for row in grid]`

2024-12-24 08:46 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return possible_values
`return permissible_set - set(row) - set(col) - set(block)`

2024-12-24 08:46 UTC, anastasiiaCher commented on homework02/sudoku.py
> +            block_check.add(solution[(i // 3) * 3 + j // 3][(i % 3) * 3 + j % 3])
Интересное решение 👍

2024-12-25 07:56 UTC, anastasiiaCher approved these changes

2024-12-25 07:56 UTC, closed without merging