Homework02 К24 1.2 Суханова М. В.
anastasiiaCher/cs102-2024 pull request #147
Opened 2024-11-27 21:55 UTC by mariapurpur

2024-11-28 12:35 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/145
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-28 13:04 UTC, amina339 commented on homework02/sudoku.py
> +    result = [grid[i][col] for i in range(len(grid))]
можно сразу брать элемент grid вместо того, чтобы обращаться по индексам через len 
result = [x[col] for x in grid]

2024-11-28 13:17 UTC, amina339 commented on homework02/sudoku.py
> +    for row in range(len(grid)):
Возможно стоило рассмотреть вариант с использованием enumerate()
    for row, p in enumerate(grid):
        for col, element in enumerate(p):
            if element == ".":
                return (row, col)

2024-11-28 13:43 UTC, amina339 commented on homework02/sudoku.py
> +        if element in find_possible_values(grid, pos):
Мне кажется строчка с элементами (1...9) лишняя, так как если pos будет пустым, то функция уже вернет нам судоку и дальше не пойдет. Можно сразу сделать цикл для возможных значений (т.к. 1...9 по-любому будут в возможных значениях, если tuple не пустой)

2024-11-28 13:53 UTC, amina339 commented on homework02/sudoku.py
> +        for j in range(1, 10, 1):
возможно стоило бы рассмотреть конструкцию с any, чтобы не расписывать каждый if

2024-11-28 13:57 UTC, amina339 commented on homework02/sudoku.py
> +        for j in range(1, 10, 1):
в цикле нет смысла писать, что нужен шаг 1, он по умолчанию такой

2024-11-28 14:11 UTC, amina339 commented on homework02/sudoku.py
> +    solved_grid = [row[:] for row in empty_grid]
Я, если честно не очень поняла идею, но как будто логичнее было бы просто написать solved_grid = solve(empty_grid), то есть просто вызвать функцию решения судоку и дать имя этому решенному судоку

2024-12-24 08:36 UTC, anastasiiaCher requested changes

2024-12-24 08:36 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return result
Можно сразу `return [values[i : i + n] for i in range(0, len(values), n)]`

2024-12-24 08:36 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return result
` return  [x[col] for x in grid]`

2024-12-24 08:36 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return result
`return [grid[row_start + i // 3][col_start + i % 3] for i in range(9)]`

2024-12-24 08:36 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return set(result)
`return all_values - used_values`
Вы ведь потом снова список в сет преобразуете

2025-01-14 10:38 UTC, anastasiiaCher approved these changes

2025-01-14 10:38 UTC, closed without merging