homework02, Панас А.А., поток 1.2
anastasiiaCher/cs102-2024 pull request #148
Opened 2024-11-28 08:56 UTC by pviskn

Реализованы функции 
group() - функция, группирующая значения в список из списков по n элементов
get_row() - функция, возвращающая значения для номера указанной строки
get_col() - функция, возвращающая значения для номера указанного столбца
get_block() - функция, возвращающая значения из квадрата, в который попадает указанная позиция
solve() - функция, которая ищет решение для пазла
find_empty_positions() - функция, которая находит первую свободную позицию
find_possible_values() - функция, которая возвращает возможные значения для найденной ранее позиции
check_solution(), для этой функции также были прописаны доктесты
generate_sudoku(N)

2024-11-28 13:12 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/151
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-28 21:42 UTC, alisakorotkova reviewed
Я просмотрела файл sudoku.py, ниже привела несколько рекомендаций по его изменению для большего соответствия PEP8.

2024-11-28 21:42 UTC, alisakorotkova commented on homework02/sudoku.py
> +                return r, c
Лучше использовать `enumerate` (особенно когда нам требуется индекс)

2024-11-28 21:42 UTC, alisakorotkova commented on homework02/sudoku.py
> +    return values
Как вариант, можно вообще обойтись без переменной `values`, а сделать так:
`return set("123456789") - set(get_row(grid, pos)) - set(get_col(grid, pos)) - set(get_block(grid, pos))`

2024-11-28 21:42 UTC, alisakorotkova commented on homework02/sudoku.py
> +    def fill_grid(grid: tp.List[tp.List[str]]) -> bool:
Лучше добавить доктесты к новой функции. И интересное решение со вложенной функцией (возможно ее стоит вынести из generate_sudoku(), но можно оставить тк она используется только в этой функции)

2024-11-28 21:42 UTC, alisakorotkova commented on homework02/sudoku.py
> +    """Если решение solution верно, то вернуть True, в противном случае False
Возможно стоит добавить доктесты для проверки функции

2024-11-28 21:42 UTC, alisakorotkova commented on homework02/sudoku.py
>      [['5', '3', '4', '6', '7', '8', '9', '1', '2'], ['6', '7', '2', '1', '9', '5', '3', '4', '8'], ['1', '9', '8', '3', '4', '2', '5', '6', '7'], ['8', '5', '9', '7', '6', '1', '4', '2', '3'], ['4',
Здесь не критично, но длина строки превышает рекомендованную, разбиение строки на несколько сделает ее более читаемой

2024-12-24 08:29 UTC, anastasiiaCher requested changes

2024-12-24 08:29 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return values
Оба варианта хорошие

2024-12-24 08:29 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    def fill_grid(grid: tp.List[tp.List[str]]) -> bool:
Для новых функций нужны новые юнит-тесты

2025-01-10 12:52 UTC, anastasiiaCher approved these changes

2025-01-10 12:52 UTC, closed without merging