Homework02 Плешнев Арсений 467106 К24 1.2
anastasiiaCher/cs102-2024 pull request #150
Opened 2024-11-28 10:34 UTC by opensource-lover

2025-01-11 16:23 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этой лабораторной - https://github.com/anastasiiaCher/cs102-2024/pull/241
Сделать ревью можно во вкладе files changed указанного пул-реквеста

2025-01-14 10:15 UTC, anastasiiaCher commented
Ревью работы коллеги хорошее

2025-01-16 14:06 UTC, enfantrich3 commented on homework02/sudoku.py
> -    grid = group(digits, 9)
Наблюдается использование двух имен (grid и ngrid) для одной и той же логики. Это создает путаницу.

2025-01-16 14:06 UTC, enfantrich3 commented on homework02/sudoku.py
> +def get_block(ngrid: tp.List[tp.List[str]], pos: tp.Tuple[int, int]) -> tp.List[str]:
get_block можно оптимизировать, используя срезы.

2025-01-16 14:06 UTC, enfantrich3 commented on homework02/sudoku.py
> -    pass
почти в каждой функции присутствует pass, хотя фактически он не нужен

2025-01-16 14:06 UTC, enfantrich3 commented on homework02/sudoku.py
> -def find_empty_positions(grid: tp.List[tp.List[str]]) -> tp.Optional[tp.Tuple[int, int]]:
find_empty_positions: Вместо магического значения (1000, 1000) лучше возвращать None, если пустых клеток нет

2025-01-25 08:13 UTC, anastasiiaCher requested changes
Если внесете правки к 28 января, баллов хватит, чтобы закрыться

2025-01-25 08:13 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return newls
Функция будет более читаемой, если оформите ее в виде спискового включения

2025-01-25 08:13 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return newls
Можно сразу так `return [ngrid[i][pos[1]] for i in range(len(ngrid))]`

2025-01-25 08:13 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        return None
Лучше:
```
if not values:
    return None
```

2025-01-25 08:13 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        if g == None:
Лучше:
```
if not solve(ngrid):
    ...
```

2025-01-25 08:13 UTC, anastasiiaCher commented on homework02/sudoku.py
> +                return False
Лучше заменить на сокращенный условный оператор и обойтись без `continue`

2025-01-25 08:13 UTC, anastasiiaCher commented on homework02/sudoku.py
> +#    grid = [["." for _ in range(9)] for _ in range(9)]
Лишним комментам не место в коде

2025-01-25 08:13 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    >>> solution = solve(grid)
Это тоже лишний коммент

2025-01-29 09:45 UTC, closed without merging