homework02 K24 1.2 Короткова А.А.
anastasiiaCher/cs102-2024 pull request #151
Opened 2024-11-28 13:05 UTC by alisakorotkova

2024-11-28 13:12 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/148
Сделать ревью можно во вкладе files changed указанного репозитория

2024-11-28 20:48 UTC, pviskn commented on homework02/sudoku.py
> +    return [row for row in grid[pos[0]]]
Достаточно просто вернуть строку по индексу

2024-11-28 20:48 UTC, pviskn commented on homework02/sudoku.py
> +    return None
вместо range(len(grid)) лучше использовать enumerate(grid), это избавит от необходимости индексировать массив вручную с помощью grid[row][col]

2024-11-28 20:48 UTC, pviskn commented on homework02/sudoku.py
> +    return g
мне кажется, что цикл while здесь можно заменить на for

2024-11-28 20:48 UTC, pviskn commented on homework02/sudoku.py
> +            return False
range(len(solution)) заменить на enumerate() или row in solution

2024-11-28 20:48 UTC, pviskn commented on homework02/sudoku.py
> +            return False
то же самое, что и в предыдущем комментарии

2024-11-28 20:51 UTC, pviskn commented on homework02/sudoku.py
> +        print("".join(grid[row][col].center(width) + ("|" if str(col) in "25" else "") for col in range(9)))
Строка слишком длинная, лучше оставить исходный вариант для лучшего восприятия и читаемости

2024-11-29 07:10 UTC, pviskn commented on homework02/sudoku.py
> +    """
нужно добавить доктесты для "плохих" головоломок-судоку

2024-12-24 08:26 UTC, anastasiiaCher requested changes

2024-12-24 08:26 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return g
Не получится

2025-01-10 12:49 UTC, anastasiiaCher approved these changes

2025-01-10 12:50 UTC, closed without merging