homework02 1.3 Калинин М.А.
anastasiiaCher/cs102-2024 pull request #156
Opened 2024-11-29 16:07 UTC by mxrget

2024-12-20 13:01 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/154
Сделать ревью можно во вкладе files changed указанного репозитория

2024-12-23 13:29 UTC, wymmsy commented on homework02/sudoku.py
> +    return empty_pos[0] if empty_pos else None
Создание массива каждый раз расходует лишнее время и ресурсы, имеет смысл реализовать через enumerate:
```
for row, p in enumerate(grid):
        for col, element in enumerate(p):
            if element == ".":
                return (row, col)
return None
```

2024-12-23 13:29 UTC, wymmsy commented on homework02/sudoku.py
> +    return option - row_values - col_values - block_values
Не критично, но можно сократить количество строк, объединив множества занятых значений уже сразу:
`token_values = set(get_row(grid, pos)) | set(get_col(grid, pos)) | set(get_block(grid, pos))`

2024-12-23 13:29 UTC, wymmsy commented on homework02/sudoku.py
> +    row, col = empty_pos
Переменные row и col логичнее объявить позднее, так как в этой if-конструкции они не используются
possible_values = find_possible_values(grid, empty_pos)
if not possible_values:
        return None

row, col = empty_pos
for val in possible_values:
        grid[row][col] = val
        if solve(grid):
            return grid

2024-12-23 13:29 UTC, wymmsy commented on homework02/sudoku.py
> +        pos = random.choice(not_empty_pos)
Мне кажется, лучше воспользоваться методом random.sample(not_empty_pos)

2024-12-23 18:40 UTC, anastasiiaCher requested changes

2024-12-23 18:40 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    for i in range(len(solution_copy)):
Лучше `enumerate`

2024-12-23 18:40 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        for j in range(len(solution_copy[0])):
Лучше `enumerate`

2024-12-23 18:40 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        pos = random.choice(not_empty_pos)
И `sample` хорошо, и `choice`

2025-01-25 07:47 UTC, closed without merging