Homework02 1.2 Куделенская Эмилия
anastasiiaCher/cs102-2024 pull request #157
Opened 2024-11-29 17:00 UTC by emopudge

2024-12-20 13:00 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/160
Сделать ревью можно во вкладе files changed указанного репозитория

2025-01-10 12:46 UTC, anastasiiaCher commented
Ревью работы коллеги в целом ок

2025-01-17 13:52 UTC, henak1 requested changes
Выполнено ревью по Homework02

2025-01-17 13:52 UTC, henak1 commented on homework02/sudoku.py
> +    return copy[pos[0]]
Для получения строки достаточно обратиться к исходному grid по индексу строки.

2025-01-17 13:52 UTC, henak1 commented on homework02/sudoku.py
> +    return mass
Можно вычислить старт мини-блока целочисленным делением на 3 и брать срез

2025-01-17 13:52 UTC, henak1 commented on homework02/sudoku.py
> +    return True
Здесь код понятный, но для каждой клетки i, j трижды вычисляется набор значений строки, столбца, блока. Можно собрать все строки/столбцы/блоки один раз.

2025-01-25 07:47 UTC, closed without merging