Homework02 К24 1.1 Эль Хеннави А.
anastasiiaCher/cs102-2024 pull request #160
Opened 2024-12-02 15:22 UTC by henak1

2024-12-20 13:00 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/157
Сделать ревью можно во вкладе files changed указанного репозитория

2025-01-03 09:27 UTC, emopudge commented on homework02/sudoku.py
>              print(line)
Использование str(col) in "25" и str(row) in "25" неочевидно. Лучше использовать явные проверки, например, col in {2, 5}

2025-01-03 09:27 UTC, emopudge commented on homework02/sudoku.py
Функция работает корректно, но можно добавить проверку на то, что длина списка values делится на n без остатка.

2025-01-03 09:27 UTC, emopudge commented on homework02/sudoku.py
> +
Нет гарантии, что удаление элементов не приведёт к появлению нескольких решений. Можно добавить проверку уникальности решения полученного судоку

2025-01-03 09:27 UTC, emopudge commented on homework02/sudoku.py
> -def generate_sudoku(N: int) -> tp.List[tp.List[str]]:
переменная n используется для обозначения количества заполненных клеток, но это не сразу понятно. можно заменить на более описательное filled_cells

2025-01-03 09:27 UTC, emopudge commented on homework02/sudoku.py
> +        print("".join(grid[row][col].center(width) + ("|" if str(col) in "25" else "") for col in range(9)))
можно разбить на несколько строк для улучшения читаемости

2025-01-10 12:41 UTC, anastasiiaCher commented on homework02/sudoku.py
>              print(line)
Не надо править

2025-01-10 12:42 UTC, anastasiiaCher commented on homework02/sudoku.py
Можно, но не обязательно

2025-01-10 12:42 UTC, anastasiiaCher commented on homework02/sudoku.py
> +
Решение у судоку либо одно, либо его нет

2025-01-10 12:43 UTC, anastasiiaCher commented on homework02/sudoku.py
> -def generate_sudoku(N: int) -> tp.List[tp.List[str]]:
Править не надо

2025-01-10 12:43 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        print("".join(grid[row][col].center(width) + ("|" if str(col) in "25" else "") for col in range(9)))
Править не надо

2025-01-10 12:46 UTC, anastasiiaCher requested changes
Вам нужно внести правки и оставить ревью коллеге

2025-01-10 12:46 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        return sorted(group) == ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
Для новых функций должны быть новые тесты

2025-01-10 12:46 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        col_values = [solution[row][col] for row in range(9)]
Можно (нужно) использовать те функции, которые вы уже раньше написали для извлечения столбца, строки и блока
Иначе зачем вы их написали?)

2025-01-10 12:46 UTC, anastasiiaCher commented on homework02/sudoku.py
> +            grid[row][col] = "."
Для новых функций нужны новые тесты

2025-01-10 12:59 UTC, emopudge commented on homework02/sudoku.py
> +        return sorted(group) == ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
а как их написать?

2025-01-25 07:47 UTC, closed without merging