Homework02 Поток: 1.1, Ахмедов Бахадыр Бахтиерович
anastasiiaCher/cs102-2024 pull request #161
Opened 2024-12-02 17:58 UTC by BahadirAhmedov

Реализовал игру Судоку

2024-12-20 12:59 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/163
Сделать ревью можно во вкладе files changed указанного репозитория

2025-01-10 20:54 UTC, mmmsha commented on homework02/sudoku.py
нужно добавить import random, который используется в функции генерации судоку
импортирование модулей делается в начале файла

2025-01-10 21:00 UTC, mmmsha commented on homework02/sudoku.py
>      # TODO: Add doctests with bad puzzles
нужно добавить доктесты

2025-01-10 21:13 UTC, mmmsha commented on homework02/sudoku.py
> +    return None
кажется, здесь можно использовать enumerate

2025-01-14 10:35 UTC, anastasiiaCher requested changes

2025-01-14 10:35 UTC, anastasiiaCher commented on homework02/sudoku.py
>      # TODO: Add doctests with bad puzzles
Необязательно

2025-01-14 10:35 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return True
Эта функция будет намного компактнее, если в ней использовать другие функции, которые уже написаны в этой работе

2025-01-14 10:35 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    """Генерация судоку, заполненного на N элементов."""
Тесты удалять не надо было

2025-01-14 10:35 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    import random
Все импорты делаются в начале файла

2025-01-14 10:35 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    def fill_grid(grid):
Для новой функции нужны тесты

2025-01-25 07:46 UTC, closed without merging