Homework02
anastasiiaCher/cs102-2024 pull request #163
Opened 2024-12-02 21:34 UTC by mmmsha

2024-12-20 12:59 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/161
Сделать ревью можно во вкладе files changed указанного репозитория

2025-01-14 10:36 UTC, anastasiiaCher commented
Ревью хорошее

2025-01-17 13:59 UTC, BahadirAhmedov requested changes
Была проделано ревью, в проекте в целом все сделано  хорошо

2025-01-17 13:59 UTC, BahadirAhmedov commented on homework02/sudoku.py
> +            values.remove((block_pos[i]))
В цикле по несколько раз делается почти одно и то же, можно обеденить логику в один цикл.

2025-01-17 13:59 UTC, BahadirAhmedov commented on homework02/sudoku.py
> +            num -= 1
Можно было бы проверять, что после удаления очередной ячейки задача остается однозначно решаемой, но это может усложнить код.

2025-01-17 13:59 UTC, BahadirAhmedov commented on homework02/sudoku.py
> +                return (i, j)
тут можно использовать enumerate

2025-01-25 08:03 UTC, closed without merging