Homework02 К24 1.1 Рожнова А.И.
anastasiiaCher/cs102-2024 pull request #164
Opened 2024-12-02 22:01 UTC by NastyaRozhnova

В этой работы были реализованы функции group(), get_row(), get_col(), get_block(), find_empty_positions(), find_possible_values(), solve(), check_solution(), generate_sudoku()

2024-12-20 12:58 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/165
Сделать ревью можно во вкладе files changed указанного репозитория

2024-12-23 11:46 UTC, anastasialbedeva reviewed
Ревью провела Лебедева Анастасия Сергеевна К24 1.3

2024-12-23 11:46 UTC, anastasialbedeva commented on homework02/sudoku.py
> +        print("".join(grid[row][col].center(width) + ("|" if str(col) in "25" else "") for col in range(9)))
Можно удалить лишние преобразования индексов строки.
Заменить текущий код на:
print("".join(grid[row][col].center(width) + ("|" if col in [2, 5] else "") for col in range(9)))
if row in [2, 5]:
    print(line)

2024-12-23 11:46 UTC, anastasialbedeva commented on homework02/sudoku.py
Можно оптимизировать код, уменьшив количество переменных
return [
    grid[r][c] 
    for r in range(3 * (row // 3), 3 * (row // 3) + 3)
    for c in range(3 * (col // 3), 3 * (col // 3) + 3)
]

2024-12-23 11:46 UTC, anastasialbedeva commented on homework02/sudoku.py
> +    random.shuffle(pos)
можно использовать random.sample для выбора случайных клеток, например
empty_cells = random.sample([(i, j) for i in range(9) for j in range(9)], 81 - n)
for x, y in empty_cells:
    grid[x][y] = "."

2024-12-23 11:46 UTC, anastasialbedeva commented on homework02/sudoku.py
> +    possible_values = find_possible_values(grid, pos)
переменная possible_values избыточна
Заменить на: for value in find_possible_values(grid, pos):

2024-12-23 11:46 UTC, anastasialbedeva commented on homework02/sudoku.py
> +        if set(row) != set("123456789"):
переменную row здесь заменить на solution[i], удалить 152 строку

2024-12-23 11:46 UTC, anastasialbedeva commented on homework02/sudoku.py
> +        if set(col) != set("123456789"):
переменную col заменить на [solution[j][i] for j in range(9)], 155 cтроку удалить

2024-12-23 18:33 UTC, anastasiiaCher requested changes

2024-12-23 18:33 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        print("".join(grid[row][col].center(width) + ("|" if str(col) in "25" else "") for col in range(9)))
Не надо трогать

2024-12-23 18:33 UTC, anastasiiaCher commented on homework02/sudoku.py
Можно, но это снизит читаемость. Можно оставить как есть

2024-12-23 18:33 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        if set(row) != set("123456789"):
Можно оставить как есть. Так лучше читается

2024-12-23 18:33 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        if set(col) != set("123456789"):
Можно оставить как есть. Так лучше читается

2024-12-23 18:33 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    solve(grid)
Лучше сохранять куда-то результат из `solve(grid)`

2024-12-23 18:33 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    random.shuffle(pos)
Можно, но в целом это два эквивалентных подхода. Можно оставить как есть

2024-12-23 18:33 UTC, anastasiiaCher commented on homework02/sudoku.py
> +            block = [solution[r][c] for r in range(block_row, block_row + 3) for c in range(block_col, block_col + 3)]
У вас есть функция `get_block`, используйте ее

2024-12-23 18:33 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        col = [solution[j][i] for j in range(9)]
Используйте `get_col`, которую сами же и написали) иначе зачем это все?)

2025-01-10 12:39 UTC, anastasiiaCher approved these changes

2025-01-10 12:40 UTC, closed without merging