Homework02 K24 1.3 Лебедева Анастасия
anastasiiaCher/cs102-2024 pull request #165
Opened 2024-12-03 18:11 UTC by anastasialbedeva

Sudoku puzzle generated and solved

2024-12-20 12:58 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/164
Сделать ревью можно во вкладе files changed указанного репозитория

2024-12-23 18:36 UTC, anastasiiaCher commented
В ревью многие комментарии предлагают снижать читаемость кода. А ее надо всеми силами повышать. Поэтому 2 из 3 за ревью. Но вы хорошо постарались.

2024-12-27 20:06 UTC, NastyaRozhnova commented on homework02/sudoku.py
> +    for index in range(9):
Для оптимизации можно использовать множества, например 

        current_col = set(get_col(solution, (0, index)))
        current_row = set(get_row(solution, (index, 0)))
        
        block_start_row = (index // 3) * 3
        block_start_col = (index % 3) * 3
        current_block = set(get_block(solution, (block_start_row, block_start_col)))

2024-12-27 20:06 UTC, NastyaRozhnova commented on homework02/sudoku.py
> +        for number in range(1, 10):
проверки можно объединить в один цикл 

        if (len(current_col) != 9 or 
            len(current_row) != 9 or 
            len(current_block) != 9:
            return False

2024-12-27 20:06 UTC, NastyaRozhnova commented on homework02/sudoku.py
> +    """Генерация судоку заполненного на N элементов"""
нет проверки на N, что если оно больше 81?

2024-12-27 20:06 UTC, NastyaRozhnova commented on homework02/sudoku.py
> +        if solve(grid):
if делает проверку, основываясь на булевой логике, что здесь не совсем подходит. лучше создать новую переменную и хранить результат вызова там 

    result = solve(grid)
    if result:
        return result

2024-12-27 20:06 UTC, NastyaRozhnova commented on homework02/sudoku.py
> +    for i in range(start_row, start_row + block_size):
вместо вложенных циклов можно использовать списковые включения, так код будет работать быстрее

    return [
        grid[i][j]
        for i in range(start_row, start_row + block_size)
        for j in range(start_col, start_col + block_size)
    ]

2025-01-10 12:38 UTC, anastasiiaCher requested changes
Надо внести правки

2025-01-10 12:38 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    new_list = list(zip(*(iter(values),) * n))
Строка перегружена до нечитаемости

2025-01-10 12:38 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    for i in range(start_row, start_row + block_size):
Хороший комментарий

2025-01-10 12:38 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        if solve(grid):
Оба варианта ок

2025-01-25 07:44 UTC, closed without merging