Homework02 K24 1.1 Данилевский Алексей
anastasiiaCher/cs102-2024 pull request #166
Opened 2024-12-03 20:33 UTC by Poleksey

2024-12-23 18:06 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/135
Сделать ревью можно во вкладе files changed указанного репозитория

2024-12-24 19:14 UTC, meranthh reviewed
Вроде добавить больше нечего, только это смогла увидеть

2024-12-24 19:14 UTC, meranthh commented on homework02/sudoku.py
> +                break
```python
for i, row in enumerate(grid):
    for k, value in enumerate(row):
        if value == ".":
            return (i, k)
 ```
 
Код может быть немного упрощен, используя enumerate. Это устранит необходимость в списке position и сразу вернет координаты первой пустой ячейки.

2024-12-24 19:14 UTC, meranthh commented on homework02/sudoku.py
> +    random.shuffle(positions)
```python
random.shuffle([(i, j) for i in range(9) for j in range(9)])
```
Эти строки могут быть упрощены и сделаны более читаемыми, если объединить их в одну строку

2025-01-10 13:11 UTC, anastasiiaCher requested changes

2025-01-10 13:11 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return two_dim
`return [values[c : c + n] for c in range(0, len(values), n)]`
Что такое `c`?

2025-01-10 13:11 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return element
Слишком много пустых строк + см. коммент к функции `group`

2025-01-10 13:11 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    values = set_fin
Так много пустых строк не надо
Давайте переменным осмысленные имена

2025-01-10 13:11 UTC, anastasiiaCher commented on homework02/sudoku.py
> +            # print(temp)
лишние комменты удаляйте

2025-01-10 13:11 UTC, anastasiiaCher commented on homework02/sudoku.py
> +            continue
Если предыдущее условие не выполнится, вы и так уйдете на следующий шаг цикла

2025-01-10 13:11 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    random.shuffle(positions)
Оба варианта ок

2025-01-24 08:50 UTC, closed without merging