Homework02 Баташов Богдан 1.3
anastasiiaCher/cs102-2024 pull request #170
Opened 2024-12-05 14:01 UTC by bogdaniidze

2024-12-20 12:57 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/180
Сделать ревью можно во вкладе files changed указанного репозитория

2024-12-22 19:37 UTC, dianuussss reviewed
программа может вызвать необработанное исключение. Следует добавить обработку ошибок:
except (FileNotFoundError, IOError) as e:
        raise ValueError(f"Ошибка при чтении файла: {e}")

2024-12-22 19:44 UTC, dianuussss commented on homework02/sudoku.py
>          puzzle = f.read()
программа может вызвать необработанное исключение. Следует добавить обработку ошибок:
return create_grid(puzzle)
except (FileNotFoundError, IOError) as e:
raise ValueError(f"Ошибка при чтении файла: {e}")

2024-12-22 19:47 UTC, dianuussss commented on homework02/sudoku.py
>  def check_solution(solution: tp.List[tp.List[str]]) -> bool:
Добавьте doctests или unit-тесты для проверки некорректных и нерешаемых головоломок. Например:
"""
    >>> check_solution([['1', '2', '3'], ['4', '5', '6'], ['7', '8', '9']])
    False
    """

2024-12-22 19:49 UTC, dianuussss commented on homework02/sudoku.py
>      """
Для воспроизводимости в generate_sudoku добавь возможность передачи seed для генератора случайных чисел.

2024-12-22 19:50 UTC, dianuussss commented on homework02/sudoku.py
>      # TODO: Add doctests with bad puzzles
Убери или обнови устаревшие комментарии если задача выполнена или больше не актуальна.

2024-12-22 19:53 UTC, dianuussss commented on homework02/sudoku.py
>      """
версия функции find_empty_positions, включающая проверку входных данных и обработку ошибок:
if not validate_grid(grid):
        raise ValueError("Некорректная сетка Судоку")

2024-12-24 09:20 UTC, anastasiiaCher requested changes

2024-12-24 09:20 UTC, anastasiiaCher commented on homework02/sudoku.py
> +                    square.append(solution[x][y])
Слишком много вложенных циклов. Стоит упростить, используя множества и функции для получения строки, столбца и блока, которые уже написаны в этой работе

2024-12-24 09:20 UTC, anastasiiaCher commented on homework02/sudoku.py
>  def check_solution(solution: tp.List[tp.List[str]]) -> bool:
Не нужно

2024-12-24 09:20 UTC, anastasiiaCher commented on homework02/sudoku.py
>      """
В каком-нибудь другом шаблоне - может быть

2024-12-24 09:20 UTC, anastasiiaCher commented on homework02/sudoku.py
>          puzzle = f.read()
В каком-нибудь другом шаблоне - может быть

2024-12-24 09:20 UTC, anastasiiaCher commented on homework02/sudoku.py
>      """
Не нужно

2024-12-24 09:20 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        return [["." for _ in range(9)] for _ in range(9)]
Пустой грид можно вынести в отдельную переменную, чтобы код не дублировался

2025-01-25 07:43 UTC, closed without merging