Homework02 Пластинина Мария 1.3
anastasiiaCher/cs102-2024 pull request #209
Opened 2024-12-19 09:56 UTC by hrxshima

2024-12-20 12:56 UTC, anastasiiaCher commented
В качестве защиты нужно сделать ревью этого репозитория - https://github.com/anastasiiaCher/cs102-2024/pull/201
Сделать ревью можно во вкладе files changed указанного репозитория

2024-12-25 21:07 UTC, hrxshima commented
> В качестве защиты нужно сделать ревью этого репозитория - #201 Сделать ревью можно во вкладе files changed указанного репозитория

[prog.md](https://github.com/user-attachments/files/18247187/prog.md)

2024-12-27 15:30 UTC, spune-mi requested changes

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
> +        mas.append(grid[i][pos[1]])
Тут лучше использовать `enumerate`

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
> +    mas.append(grid[a + 2][b + 2])
Лучше сделать при помощи вложенных циклов или срезами

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
> +    mas = []
Непонятно, что такое mas. Я вижу, что это массив, но название не говорит мне, зачем он нужен

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
> +    mas = []
Опять нейминг

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
> +                return i, j
Тут можно использовать `enumerate` + find()

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
> +    return all
1) Нейминг переменных
2) методы можно последовательно накладывать следующим образом: `data.method(val1).method(val2).method...`

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
> +        for j in range(len(solution)):
Лучше использовать `enumerate`
См. https://www.geeksforgeeks.org/enumerate-in-python/

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
> +                return False
Нейминг, непонятно что каждая переменная и сравнение означает. Можно объединить весь этот блок кода в один большой преждевременный return

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
> +        k = 0
Нейминг: что такое k? Зачем эта переменная? 
Можно упростить: `k = 81 - N if N < 81 else 0`

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
> +        mas[t][p] = "."
Что если мы хотим очень много пропусков? Придется ждать случайное количество времени. 

Вместо этого лучше сгенерировать маску и потом применить ее на судоку.

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
>      pass
Лучше убрать

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
>      pass
Лучше убрать

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
>      pass
Лучше убрать

2024-12-27 15:30 UTC, spune-mi commented on homework02/sudoku.py
>      pass
)

2025-01-10 12:21 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        mas[t][p] = "."
Да, так лучше, но и текущий вариант имеет место быть

2025-01-10 12:21 UTC, anastasiiaCher commented on homework02/sudoku.py
>      pass
Нужно, а не просто лучше

2025-01-10 12:23 UTC, anastasiiaCher commented
Ваше ревью не совсем про pep8, но зачтено. Вам правки предложены годные

2025-01-25 07:39 UTC, closed without merging